set("EVENT__DISABLE_TESTS" "ON" CACHE INTERNAL "")
set("EVENT__DISABLE_SAMPLES" "ON" CACHE INTERNAL "")
set("EVENT__DISABLE_REGRESS" "ON" CACHE INTERNAL "")
set("EVENT__DISABLE_BENCHMARK" "ON" CACHE INTERNAL "")
